steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'portao-cerveja-erp'
      - '--source=.'
      - '--region=us-west1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--project=gen-lang-client-0756600199'
      - '--update-env-vars=GEMINI_API_KEY=$_GEMINI_API_KEY'

substitutions:
  _GEMINI_API_KEY: ''

options:
  logging: CLOUD_LOGGING_ONLY
